from django.urls import path 
from . import views 
urlpatterns = [ 
    path('', views.index, name= "books.index"), 
    path('list_books/', views.list_books, name= "books.list_books"), 
    path('<int:bookId>/', views.viewbook, name="books.view_one_book"), 
    path('aboutus/', views.aboutus, name="books.aboutus"), 
    path('html5/links', views.links, name='books.links'),
    path('html5/text/formatting', views.formatting, name='books.formatting'),
    path('html5/listing', views.listing, name='books.listing'),
    path('html5/tables', views.tables, name='books.tables'),
    path('search', views.search, name='books.search'),
    path('simple/query', views.simple_query),
    path('complex/query', views.complex_query),
    path('lab8/task1', views.lab8_task1),
    path('lab8/task2', views.lab8_task2),
    path('lab8/task3', views.lab8_task3),
    path('lab8/task4', views.lab8_task4),
    path('lab8/task5', views.lab8_task5),
    path('lab8/task7', views.lab8_task7),
    path('lab9_part1/listbooks', views.list_books_part1, name='lab10_list_books'),
    path('lab9_part1/addbook', views.add_book, name='add_book'),
    path('lab9_part1/editbook/<int:id>', views.edit_book, name='edit_book'),
    path('lab9_part1/deletebook/<int:id>', views.delete_book, name='delete_book'),
    path('lab9_part2/listbooks', views.list_books_part2, name='list_books_part2'),
    path('lab9_part2/addbook', views.add_book_part2, name='add_book_part2'),
    path('lab9_part2/editbook/<int:id>', views.edit_book_part2, name='edit_book_part2'),
    path('lab9_part2/deletebook/<int:id>', views.delete_book_part2, name='delete_book_part2'),
] 